// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_animal.cpp"
#include "EWIEGA46WW/moc_canine.cpp"
#include "EWIEGA46WW/moc_fenine.cpp"
#include "EWIEGA46WW/moc_mammal.cpp"
#include "EWIEGA46WW/moc_monster.cpp"
